### ISSUE TITLE
pip install is incomplete

### ISSUE THREAD

**Issue by SpecCRA** [swar/nba_api#1]
Is anyone else missing the static object after installing through pip? 

I'm on macOS version 10.13.6. 

Btw, thanks for making this!!! I've been dying to use nba_py again.

**Comment by swar** [comment]
Would you be able to give me the error message that you are getting? I was able to successfully install from pip on Windows.

**Comment by SpecCRA** [comment]
@swar There isn't any error message upon installation, but the folder for static doesn't exist. I only figured this out when I was tried it in code, and the module didn't exist.

**Comment by swar** [comment]
In my excitement to release this last night, I totally forgot to add __init__.py to that static folder. I went ahead and released v1.0.2 (as well as 1.0.1 because of I needed to add "__all__" with the module names.)

Please feel free to reinstall the package and let me know if it works! 

`pip install nba_api --upgrade`

**Comment by SpecCRA** [comment]
Looks like it's all there. Thanks for the quick fix!
