### ISSUE TITLE
stats endpoints not working?

### ISSUE THREAD

**Issue by jtpavlock** [swar/nba_api#106]
Are the stats endpoints not working for anyone else? Not sure if down or something is wrong on my end.

**Comment by davidjbauer** [comment]
I am getting a ConnectionError exception when trying to use the teamyearbyyearstats endpoint. It seems like it is an issue with stats.nba.com, since my HTTP requests are also not working or only working occasionally.

**Comment by jtpavlock** [comment]
I don't think stats.nba.com/stats exists anymore

**Comment by Cellular-** [comment]
I'm looping through a csv file that contains all the player ids for players in this season. Then, I'm calling the playergamelog endpoint for each player. Each loop, the script is paused so I'm not throttled but even then I am getting alot of errors related to "Caused by NewConnectionError" and "Failed to establish a new connection: Network is unreachable"

It seems like I'm either not pausing the script long enough or the endpoints are now being throttled in some way. Anyone else having these issues?

**Comment by gidfs** [comment]
From what I can tell, stats.nba.com/stats still exists. Its just that they've started restricting it. You have to mock it with a referer: 

`curl 'https://stats.nba.com/stats/videoeventsasset?GameEventID=420&GameID=0021900248' -H 'Referer: https://stats.nba.com/events'` works

I have a problem as well though. This request works on my local, but it hangs when made from a heroku dyno. For the life of me i cant figure out why. Anyone have any suggestions?

**Comment by jtpavlock** [comment]
Apparently they ban many cloud provider IPs. Maybe try a proxy?

**Comment by swar** [comment]
The newest version should be working as expected with the referrer in place. @gidfs 

@jtpavlock is correct that most cloud providers are banned and you would need to pass it a valid proxy.

Does this issue still persist?

Sorry I have been MIA with the holidays and busy work schedule.

**Comment by gidfs** [comment]
All good. Yup, proxy worked.

**Comment by swar** [comment]
Feel free to reopen or create a new ticket if you still have questions.

**Comment by jakesanghavi** [comment]
How do I find the URL the video of for any given play with VIDEO_AVAILABLE_FLAG ==1? Doesn't come up when I scrape my dataframe.
