### ISSUE TITLE
Is there a way to get missed shots?

### ISSUE THREAD

**Issue by JonStep123** [swar/nba_api#107]
I've been using ShotChartDetail and I noticed that it only returns shots that are made, is there a way to make it include missed shots as well?

**Comment by swar** [comment]
Can you post the code snippet that you are using?

https://github.com/swar/nba_api/blob/master/docs/nba_api/stats/endpoints/shotchartdetail.md

I believe you can get this working if you pass `context_measure_simple='FGA` because I believe `FGM` is default.

Sorry I have been MIA with work and the holidays. @JonStep123

**Comment by swar** [comment]
Feel free to reopen or create a new ticket if you still have questions.
