### ISSUE TITLE
Anyone tried G league?

### ISSUE THREAD

**Issue by agoola** [swar/nba_api#111]
any success?

**Comment by swar** [comment]
@agoola it looks like it might not work because the URL is completely different for GLeague stats.

https://stats.gleague.nba.com/leaders/

This might be a new section to explore because I don't know how else we would access this data unless we can specify GLeague on the original NBA Stats API.

Also sorry for the delay in response, I have been super busy with work and the holidays

**Comment by swar** [comment]
Feel free to reopen or create a new ticket if you still have questions.
