### ISSUE TITLE
Insert the actual parameter names in the documentation

### ISSUE THREAD

**Issue by micric** [swar/nba_api#19]
Adding the actual variable name to the url name in the documentation of the different endpoints would facilitate the usage of the package.

**Comment by micric** [comment]
For example in the teamyearbyyearstats endpoint, the Parameters are named LeagueID, PerMode, SeasonType and TeamID, but in python the actual variables are called league_id, per_mode_simple, season_type_all_star and team_id. 
`    stat = teamyearbyyearstats.TeamYearByYearStats(team_id=teamID, league_id = "00", per_mode_simple="Totals",
                                                   season_type_all_star="Regular Season").team_stats.get_data_frame()`

**Comment by swar** [comment]
I agree. This is something that definitely needs to be added in.

**Comment by mchauta** [comment]
Yes, I think this is important. As of now is there anyway to find out what parameter names we can pass in? 

I'm getting unexpected arguments errors when I do this:
`playergamelog.PlayerGameLog(player_id=id, season=year, season_type=type)`

I know 'player_id' is right but I'm just guessing on the others.

**Comment by mchauta** [comment]
Ok I found them in the files, but it would be nice to have them in the docs. Also, I don't understand why "Season" is season_all and SeasonType is "season_type_all_star"? for PlayerGameLog.py

**Comment by swar** [comment]
@mchauta 
https://github.com/swar/nba_api/blob/master/docs/nba_api/stats/library/parameters.md

The reason for multiple parameter names was to standardize the regex patterns being returned. Not all season_type variables accept the same values, and thus I had to break it out into other variables.

https://github.com/swar/nba_api/blob/master/docs/nba_api/stats/library/parameters.md
Here is a better picture of all the different regex patterns being spit out for variables.

**Comment by swar** [comment]
Also with the holiday season here, I am hoping to find a good break to catch up with some of these issues and knock a few of them out. So this is still pending and will be added.

**Comment by swar** [comment]
Changes have been implemented as of [v1.0.7](https://github.com/swar/nba_api/blob/master/docs/version_log.md#v107)

I made more changes to the docs to make it a bit easier to read, specifically the endpoint page.

**Changes include:**
- Link to the python file at the top of the documentation page. I realize it's a bit of a hurdle to jump between the pages so having a link will make it easier to go to the code.
- Link to the Parameter documentation bookmarked to each individual API Parameter. This is to easily view the information for that Parameter.
- Adding Python Parameter Variable so that you know what name to use in the parameters.

Let me know your thoughts and changes you want to see. Definitely open to adding information and changing formatting if needed.
