### ISSUE TITLE
Is this library considered maintained?

### ISSUE THREAD

**Issue by vidhanio** [swar/nba_api#254]
Hi!

There are a lot of dead endpoints which I am wondering will be cleaned up at some point. There hasn't been a large update in a while, and just wanted to ask whether this library will be updated again at some point.

**Comment by Davidcparrar** [comment]
+1

**Comment by rsforbes** [comment]
@vidhanio - Yes. The library is still maintained; however, finding the time is a challenge. lol. I'll see what I can do in the next 30 days to get in some updates. If you can provide some of those endpoints which you are having issues with, that would help. Also, feel free to make a PR we'll always take the help. :-D

**Comment by TK05** [comment]
@vidhanio @Davidcparrar, which endpoints in particular are dead? `BoxScoreDefensive`, `BoxScoreMatchups`, `BoxScoreSimilarityScore` and `ShotChartLineupDetail` currently fail tests.

It has been a while since I looked at this code base and NBA API endpoints in general but the `stats.nba.com` is unofficial meaning there's no documentation of endpoints and no change log to track changes. All updates and deprecation to the underlying API endpoints is done silently which requires that users report dead endpoints and changes to endpoints in general.

It does look like a number of endpoints have been updated at some point. Many `v1` endpoints are now `v2` and many `v2` endpoints are now `v3`. From a brief check, it looks like all the advanced stats (tables from nba.com/stats) use the "old" schema. Many/all game specific endpoints (nba.com/game pages) use the newer schema which mirrors the existing `nba_api.live.nba.endpoints` endpoints.
