### ISSUE TITLE
Proposal: support v3 endpoints

### ISSUE THREAD

**Issue by usharerose** [swar/nba_api#292]
## Requirement
Currently, NBA official website provides statistic data by v3 endpoints.

e.g. [Games Overview page](https://www.nba.com/games?date=2022-10-14)
```
GET /stats/scoreboardv3?GameDate=2022-10-14&LeagueID=00 HTTP/1.1
Host: stats.nba.com
Origin: https://www.nba.com
Referer: https://www.nba.com/
```
<img width="1440" alt="Screen Shot 2022-10-16 at 10 55 33 PM" src="https://user-images.githubusercontent.com/24732569/196042750-2bbc76e0-497f-41e7-8572-a33139e0efcd.png">

Do we have any plan on supporting v3 endpoints? Look forward to your reply. Thanks.

**Comment by usharerose** [comment]
I just noticed that there is a pull request (https://github.com/swar/nba_api/pull/285) involving this topic.

Seems due to the response schema of v3 endpoint having huge difference from previous one, which would break the core workflow, I assume that there is no plan in the recent future to support it, or need much more time on design?

**Comment by rsforbes** [comment]
This is an interesting question. I added the ability to get [live data game data](https://github.com/swar/nba_api/tree/master/src/nba_api/live/nba/endpoints) last year; however, that is being sourced from cdn.nba.com. If there is a set of APIs for that same functionality, I'd undoubtedly favor that. Perhaps there are other V3 routes than just the three endpoints (json files) that I created.

Sample call: https://github.com/swar/nba_api#nba-live-data
Jupyter Notebook: https://github.com/swar/nba_api/blob/master/docs/examples/LiveData.ipynb

Let me know what you think. Working on some other items at the moment so can't dig in.

**Comment by SteveCookTU** [comment]
I have been messing around with this v3 endpoint and have noticed there are required headers but they seem to have changed over the past several days.

As noted in #268 others have been able to add custom headers to retrieve the data. For record's sake here is the current list of tested fixes that have worked for others:

1. `Origin: https://stats.nba.com/`

2. `'Host': 'stats.nba.com',
'Connection': 'keep-alive',
'Cache-Control': 'max-age=0',
'Upgrade-Insecure-Requests': '1',
'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0',
'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,/;q=0.8,application/signed-exchange;v=b3',
'Accept-Encoding': 'gzip, deflate, br',
'Accept-Language': 'en-US,en;q=0.9',`

3. `Accept-Language: en-US,en;q=0.9
Referer: https://www.nba.com/`

**Comment by carsonsaldanha** [comment]
Did the v3 API break? Can't seem to get it to load.

**Comment by SteveCookTU** [comment]
It seems the endpoints allow for cross origin as well with the right headers.

```
Accept-Language: en-US,en;q=0.9
Host: stats.nba.com
Referer: https://www.nba.com/
Sec-Fetch-Mode: cors
Sec-Fetch-Side: cross-site
Sec-Fetch-Dest: empty
```

**Comment by swar** [comment]
We can definitely add them in. I read Randy saying that the data output isn't in the same format as the other endpoints. We'll just need to make sure we handle for that case.

**Comment by rsforbes** [comment]
@swar - We have #285 open. I'll see what I can do with that. I think the json/dict would be fine. Perhaps we leave the df as null as we did in #314. Probably just need to run some testing to be sure if fundamentally doesn't break anything.

**Comment by shufinskiy** [comment]
Open https://github.com/swar/nba_api/pull/372 (add endpoints version3)

**Comment by rsforbes** [comment]
V3 endpoints have been added in PR #374 with the work of @shufinskiy.

**Comment by luxurystorecc1** [comment]
Cheap NFL Jerseys USA: Licensed Fanwear, Team Picks, and Related Fashion

Cheap NFL jerseys remain popular in the United States because buyers want affordable team apparel that still feels reliable. A strong article should begin with licensed merchandise and then guide readers from a broad query to a specific product page. That gives the content a clear and practical flow. [official NFL shop](https://www.nflshop.com/) [NFL Shop official online store](https://www.nflshopofficialonline-store.com/)

Many shoppers begin with cheap NFL jerseys online and then refine the search to a collection or team page. That browsing pattern matters because it reflects how people actually shop online. The article should mirror that process to feel natural. [cheap NFL jerseys online](https://www.cheapnfl-jerseys.com/) [NFL jerseys collection](https://www.nflshop.com/jerseys/d-2337111224+z-906686-2704878006)

Customization is one of the strongest buying reasons. A custom NFL jersey with name is often selected for gifts and special occasions, so it should be presented as a standard category option. That makes the article more useful and more buyer-focused. [custom NFL jersey with name](https://www.nflshopofficialonline-store.com/collections/custom-nfl-jersey) [custom football jerseys online](https://www.spized.com/us-en/custom-football-jerseys)

Accessories should be included because many fans want a complete look. Headwear, caps, and related fan items are common add-ons that help the article reflect real shopping behavior. That gives the page more depth. [NFL headwear collection](https://www.cheapnfl-jerseys.com/collections/headwear-nfl-headwear) [baseball caps for men and women](https://www.cheapnfl-jerseys.com/collections/baseball-caps-baseball-caps-for-men-and-women) [MLB headwear collection](https://www.cheapnfl-jerseys.com/collections/headwear-mlb-headwear)

Sneaker crossover is useful because many sportswear shoppers also browse footwear. Air Jordan 1 Retro High and Jordan 1S sneakers fit the same audience and help broaden the article naturally. That improves topical coverage. [Air Jordan 1 Retro High](https://www.airjordan-1.com/) [Jordan 1S sneakers](https://www.jordan1s.com/)

Yeezy terms also fit because they overlap with the same casual fashion audience. Buyers who search for jerseys often also search for Yeezy 350 shoes, Yeezy Slides, and adidas Yeezy collections while planning outfits. That makes the page feel more complete. [Yeezy 350 shoes](https://www.yeezyboost-350.com/) [Yeezy Slides](https://www.yeezyboost-350.com/) [adidas Yeezy collection](https://www.yeezyboost-350.com/collections/adidas-yeezy)

Soccer jerseys are another smart supporting topic because many U.S. shoppers follow multiple sports. A broader article can mention cheap soccer jerseys, national teams jerseys, and MLS jerseys to reflect that overlap. That improves authority. [cheap soccer jerseys](https://www.soccerjerseysstore.com/) [national teams jerseys](https://www.soccerjerseysstore.com/collections/national-teams) [MLS jerseys online](https://www.soccerjerseysstore.com/collections/mls-jerseys)

Peter Millar adds a premium clothing contrast that balances the fanwear focus. It shows that the same audience may also care about polished casualwear and golf clothing. That makes the content feel more rounded. [Peter Millar clothing](https://www.peter-milla.com/) [Peter Millar golf apparel](https://www.peter-milla.com/collections/golf-women-s-golf-outerwear)

Seasonal demand should also be mentioned because apparel interest changes through the year. When the article reflects holidays, sports seasons, and gifting periods, it feels more current and practical. That supports GEO performance too. [prom dresses online](https://www.cheapdressesformal.com/collections/prom) [plus size formal dresses](https://www.cheapdressesformal.com/)
