### ISSUE TITLE
[Bug]: PlayerGameLog is returning empty dataframes.

### ISSUE THREAD

**Issue by willyamwu** [swar/nba_api#378]
### NBA API Version

V1.3.0

### Issue

Since around 2 months ago, I've been using PlayerGameLog to get the stats of a player from a certain game. It has worked fine up until recently when I tested it and it began returning empty data frames. I checked the parameters I was passing through the PlayerGameLog, and they all seemed valid. Moreover, I'm pretty sure that PlayerGameLog is still an active endpoint. I'm not sure if I am making a silly mistake.

Moreover, if there is an endpoint that gets all the stats of players who played in a specific game, please let me know.

Thank you for your help!

### Code

```
gamelog = PlayerGameLog(player_id=player, date_to_nullable=CONSTANTS.yesterday_date_string, date_from_nullable=CONSTANTS.yesterday_date_string)
bronGame = gamelog.get_data_frames()[0]
```

**Comment by rsforbes** [comment]
@willyamwu - The issue here is that [Season.default](https://github.com/swar/nba_api/blob/3a4bb00b3d63dc9d0c14e4a1d104f4ca0f4097d6/src/nba_api/stats/library/parameters.py#L645) is a calculated value based on the year.


The following will work
```
# PlayerGameLog
from nba_api.stats.endpoints.playergamelog import PlayerGameLog
PlayerGameLog(player_id = 1631105, season="2022-23").get_data_frames()[0]
```
![image](https://github.com/swar/nba_api/assets/847338/414890e9-83b0-48e4-877f-dbb956936971)
