### ISSUE TITLE
Changing default values: LastNGames & Default

### ISSUE THREAD

**Issue by 903124** [swar/nba_api#4]
Last_n_game default should be 0 not 10

**Comment by 903124** [comment]
Also period default should be 0 too.

**Comment by swar** [comment]
I need to compare these the default values in the endpoint analysis tool. I can't remember if I had them set to their defaults for a specific reason. If I did, it's because it was failing endpoints in the analysis tool.

Will look into this further sometime this week when I get a chance to run the analysis tool.

**Comment by swar** [comment]
Added changes to commit https://github.com/swar/nba_api/commit/bb8484a4c024c812a33a93ab592804fd54fbf69c

Slotted for release in next update.

**Comment by swar** [comment]
This is active as of [`v1.0.5`](https://github.com/swar/nba_api/releases/tag/v1.0.5).
