### ISSUE TITLE
[Bug]: Incorrect Data for Team Rankings

### ISSUE THREAD

**Issue by AdityaRao127** [swar/nba_api#441]
### NBA API Version

1.4.1

### Issue

All team-ranked categories return 1, for the 2023-24 NBA season. 

For example, these gave 1st rank for all 30 teams, when tested several times: 
- three-point percentage rank 
- three-point field goals made rank
- field-goal percentage rank

This data is supposed to be accessible through the `teamdashboardbyshootingsplits.py` and `teamdashboardbygeneralsplits.py`

**Comment by rsforbes** [comment]
@AdityaRao127 - Will get this look at this weekend.

**Comment by AdityaRao127** [comment]
Hi @rsforbes , just wanted to check in on this.

**Comment by rsforbes** [comment]
@AdityaRao127 - Apologies for the delay. Finally got around to running the code. 

Educated Guess: Because you are pulling a single team, which is the intent of the call, all teams ranks will be `1`. The reason? There is only one team, and that team ranks first. What does it mean? The fields are essentially useless.

Site Location: In general, ever call has some type of web page in front of it. I was able to locate the `TeamDashboardByShootingSplits` and `TeamDashboardByGeneralSplits` on the following pages:

- [TeamDashboardByShootingSplits](https://www.nba.com/stats/team/1610612741/shooting?SeasonType=Regular+Season&Season=2022-23)
- [TeamDashboardByGeneralSplits](https://www.nba.com/stats/team/1610612741/traditional?Season=2022-23&SeasonType=Regular+Season)

Of interest you to is the lack of `rank` on these pages futher indicating that what is being returned in the response is likely just irrelevant data.

If you are trying to rank teams, depending on your work, you might look at the LeagueDashTeamStats call. It may provide the data you seek. [LeagueDashTeamStats](https://www.nba.com/stats/teams/traditional) is one of the main stats pages for teams.

Hopefully that helps put some context around the calls you are using and perhaps provides an alternative.
