### ISSUE TITLE
json.loads()

### ISSUE THREAD

**Issue by michael-petersen** [swar/nba_api#47]
This is similar to #5 in the error (i.e. json.decoder.JSONDecodeError), but the fix is different. In my implementation of anaconda (Mac OS X, python 3.6.5), I needed to change nba_api/library/http.py line 38, 

return json.loads(self._response)

to 

return requests.get(self._url).json()

and then it works as expected. You could put this fix in valid_json(), probably, not sure what position is best.

**Comment by swar** [comment]
What data is being returned to you in `return requests.get(self._url).json()`? I'm curious to see if it parses XML related errors to JSON, which maybe I should be doing as well.

One caveat with your solution is that it would need to make a request every single time to the url when calling the function instead of loading the data into `._response`.

Although, maybe there's a better way for the spider to error out when the return response is invalid. Maybe creating custom exceptions? No idea will need to brainstorm on possible solutions.


Unrelated note: I went to UMass too!
