### ISSUE TITLE
SynergyPlayTypes not returning a data set

### ISSUE THREAD

**Issue by MDSnurp** [swar/nba_api#68]
Tried to use the new SynergyPlayTypes endpoint today, but it isn't returning a data set. It's behaving the same as it is on [doc page](https://stats.nba.com/stats/synergyplaytypes?LeagueID=00&PerMode=Totals&PlayType=&PlayerOrTeam=T&SeasonType=Regular+Season&SeasonYear=2018-19&TypeGrouping=)

**Comment by swar** [comment]
Can you provide what parameters you were trying to input?

**Comment by TK05** [comment]
In order to return actual useful data, you'll have to provide both a `TypeGrouping` and `PlayType` parameter. The API is valid without those (they're not required) but they are required if you want any actual data.

The variable names are `type_grouping_nullable` and `play_type_nullable`. See (synergyplaytypes.md)[https://github.com/swar/nba_api/blob/master/docs/nba_api/stats/endpoints/synergyplaytypes.md]

You can either provide them with valid strings but they're also included as built in parameters in (`parameters.py`)[https://github.com/swar/nba_api/blob/master/nba_api/stats/library/parameters.py] - See (parameters.md)[https://github.com/swar/nba_api/blob/master/docs/nba_api/stats/library/parameters.md]

You can try something like:
```
from nba_api.stats.endpoints.synergyplaytypes import SynergyPlayTypes

stats = SynergyPlayTypes(type_grouping_nullable='offensive', play_type_nullable='Transition').get_dict()
```

which will return a dictionary of team offensive transition play types

Or with built in parameters:
```
from nba_api.stats.endpoints.synergyplaytypes import SyngergyPlayTypes
from nba_api.stats.library.parameters import PlayType, TypeGrouping

stats = SynergyPlayTypes(type_grouping_nullable=TypeGrouping.offensive, play_type_nullable=PlayType.transition).get_dict()
```

which will return the same thing but uses built in parameters

**Comment by MDSnurp** [comment]
> 
> 
> Can you provide what parameters you were trying to input?

I had tried most combinations of the parameters through playing with the example, but the only I hadn't tried was type_grouping as I wasn't entirely sure what it was and didn't think to check the parameters documentation. Thanks to @TK05 for pointing that out
