### ISSUE TITLE
PBP thoughts

### ISSUE THREAD

**Issue by chisox721** [swar/nba_api#84]
First off - Great work on this. Most thorough and well put together NBA package I've used. No actual issues thus far so feel free to close this off the bat but I do have a couple thoughts. 

1. It looks like you already did the work for extracting referee name from the descriptions (unless I misinterpreted the script). Will that be a future addition? I've been planning to do some work with regard to ref foul tendencies.

2. Along those same lines, being able to differentiate between non-shooting, 2pt shooting fouls and 3pt shooting fouls would be helpful. (shot distance would be even better but doesn't look like the the nba source even provides it).

It's no problem for me to do this stuff on my end but figure if the additions are pending I could just wait. Thanks again.

**Comment by swar** [comment]
Thank you! I hope you continue using it. :smile: 

1.) Extracting referee's name was actually done by @rsforbes. So a big thanks to him for all the regex patterns over here: https://github.com/swar/nba_api/blob/master/nba_api/stats/library/playbyplayregex.py

I believe this file should already be apart of the library and can be accessed with the following import statement.

```python
from nba_api.stats.library.playbyplayregex import {whatever you need}
```

It's funny that you mention this though, because I was working on the exact same thing last week.


2.) I am unsure if this data is available, because it just indicates the foul type for the most part. Since it doesn't say if a shot is performed, but instead a foul was made.


Also, I don't think we plan to add any built in parsing for nba_api. That would require a lot of unique handling of endpoints, and the package, as it stands, was not designed in a way to handle custom parsing.

Although, I believe you should be able to access most of what you want to do, with the above import.

**Comment by rsforbes** [comment]
@chiaox721 - I've created a number of tests that provide some good examples of using all of the regex for the play by play. There are a number of things that you are looking for in there such at the 2pt vs 3pt, distance, ref, foul type, etc. Note that the NBA does not always provide the full amount of information. 

The tests show how to deal with all of the data. The data is based on real data mined through the season. Thwt is in the test data set. Note that there could be some edge cases not yet covered as new data is provided in the actual feed. Several of us have been working from time to time on figuring out to to automate connection to the NBA from integration servers, but we believe that the NBA blocks these CI systems.This type of integration would be helpful to alert on that new data, update the regex, and capture a test for it.

Let me know if you have any questions. It took quite a bit of time to pull them all together so I'm pretty familiar with the play by play feed. Lol.

https://github.com/swar/nba_api/tree/master/tests/stats/library/playbyplay

**Comment by chisox721** [comment]
@rsforbes Great job on the regex. Did some work over the weekend and so far the only issue I had was an attribute error when pulling free throw data. I'll paste my code but it hung for a Markieff Morris attempt - his name outputs as "Mark Morris" in the PBP so I'm assuming the 2 names is the problem. No worries if I need to work around it on my end but if you have any suggestions I'd appreciate it. 

```
        if description is not None and play['EVENTMSGTYPE'] == 3:
            try:
                search_result = re_free_throw_made.search(description)
                play['FT_TYPE'] = search_result.group('free_throw_type')[-1:] 
            except AttributeError:
                search_result = re_free_throw_miss.search(description)
                play['FT_TYPE'] = search_result.group('free_throw_type')[-1:]
```

**Comment by rsforbes** [comment]
@swar - Was working through this today. This should be changed from 'question' to 'bug'. How I'm going to solve it is still a mystery.

The first instance I came across was 

"Beal 16' Step Back Jump Shot (17 PTS) (Mark Morris 2 AST)"

The issue is with a Player having two names. In this case 'Mark Morris'

When ran against data such as

Mark Morris Step Back Jump Shot (17 PTS)

The regex parses it as 

player = Mark
field_goal_type = Morris Step Back Jump Shot

We should be getting 

player = Mark Morris
field_goal_type = Step Back Jump Shot.

**Comment by rsforbes** [comment]
@chisox721 - Finally the NBA season approaches and the thrill of writing code for it. I fixed every instance of player name issues, _with the exception of turnovers_ 😭, in my latest PR to @swar . I took a wee bit different approach. We'll have to see as the season progresses. It's all based on how they represent their data. I already found one change in how they are representing Full Timeouts. I'm going to set up a job (_somewhere_) to run my integration tests to see if I can't hit the nba_api each day to loop through yesterdays games looking for issues. Time will tell. I'll continue to press on for the turnovers to see if I can somehow get that fixed. I may have to just created some variable to hold these anomalies as parsing something like `Mark Morris Double Dribble` doesn't parse to well when their's nothing to anchor to.

**Comment by rsforbes** [comment]
@chisox721 / @swar - So I had to bow down to Mark Morris. There's no way to parse the difference without actually _knowing_ either the players name or all of the types of turnovers. So be it. Either way, it's fixed and the only _hard coding_ I had to do was in the section of player turnover. Pretty happy with the code, not so much with the NBA throwing a curve ball. That's what you get when you're parsing strings. LOL. Going to be running some integrations tests tomorrow over data to see if anything interesting pops up.

This should be good for now and should be able to be closed.

**Comment by swar** [comment]
I will get to the PR later this week or during the weekend.

That's a very odd case with the Morris brothers and I don't think there will be a better way to handle it

**Comment by chisox721** [comment]
@rsforbes @swar Just now getting back into this and wanted to say thanks for putting the time in. I had created a workaround on my end but it's nice to know the issue was due to something other than me writing bad code (for once!). Great job guys.
